# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: node -v && npm -v
  displayName: 'Check node & npm versions'

- script: npm i
  displayName: 'Install packages'

- script: npm run all-check
  displayName: 'Test, Lint, TSC'

- script: npm run rollup && npm run build
  displayName: 'Build'