version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    branches:
      only:
        - master
    docker:
      - image: deptno/circleci-awscli-node8:0.1
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run: # run tests
          name: all-check
          command: npm run all-check
      - run: # run tests
          name: build
          command: npm run rollup && npm run build